### ISSUE TITLE
newest yargs dependency breaks kss-node because it does not follow semver

### ISSUE THREAD

**Issue by rkichenama** [kss-node/kss-node#240] opened 2015-11-17 21:47 UTC
My project has been great, using kss-node to generate a demo styleguide, until I needed to build in a new environment. npm install, which would go through my package.json to install min versions of modules, finds that I do not have kss in my node_modules folder and pulls v2.1.0 down.

My entire build fails. The command line './node_modules/kss/bin/kss-node --config kss-config.json'  breaks, stating unknown xdemo option. I have tried many ways, but it seems the --config flag is being ignored. My config is too complicated to enter into the command line, and even if I did, only the version and help flags seem to be functioning.

If there is something different from May's v2.1.0 and todays v2.1.0, shouldn't there be a version increment? Is the config and other cli flags being deprecated or removed?

**Comment by pcraum** [comment] 2015-11-18 10:34
+1

**Comment by pcraum** [comment] 2015-11-18 13:50
@rkichenama may be it's not kss-node, it can be a dependency ... no idea which one. Btw i downgraded our version to 2.0.2 and no more  xdemo option problem ;)

**Comment by JeremiePat** [comment] 2015-11-19 17:29
+1

There is a high chance that it's a dependency issue. One of my colleague face the issue where I don't, and there are differences in our dependency tree:

Good dependency tree:
```
├─┬ kss@2.1.0
│ ├─┬ glob@4.5.3
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@2.0.8
│ │ │ └─┬ brace-expansion@1.1.0
│ │ │   ├── balanced-match@0.2.0
│ │ │   └── concat-map@0.0.1
│ │ └─┬ once@1.3.2
│ │   └── wrappy@1.0.1
│ ├─┬ handlebars@3.0.3
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.3
│ │ ├─┬ source-map@0.1.43
│ │ │ └── amdefine@0.1.0
│ │ └─┬ uglify-js@2.3.6
│ │   ├── async@0.2.10
│ │   └─┬ optimist@0.3.7
│ │     └── wordwrap@0.0.3
│ ├── marked@0.3.3
│ ├─┬ natural@0.1.29
│ │ ├── apparatus@0.0.9
│ │ ├── sylvester@0.0.21
│ │ └── underscore@1.8.3
│ ├── wrench@1.5.8
│ └─┬ yargs@3.9.1
│   ├── camelcase@1.1.0
│   ├─┬ cliui@2.1.0
│   │ ├─┬ center-align@0.1.1
│   │ │ └─┬ align-text@0.1.1
│   │ │   ├── kind-of@1.1.0
│   │ │   ├── longest@1.0.1
│   │ │   └── repeat-string@1.5.2
│   │ ├─┬ right-align@0.1.1
│   │ │ └─┬ align-text@0.1.1
│   │ │   ├── kind-of@1.1.0
│   │ │   ├── longest@1.0.1
│   │ │   └── repeat-string@1.5.2
│   │ └── wordwrap@0.0.2
│   ├── decamelize@1.0.0
│   └── window-size@0.1.0
```

Bad dependency tree:
```
├─┬ kss@2.1.0
│ ├─┬ glob@4.5.3
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@2.0.8
│ │ │ └─┬ brace-expansion@1.1.0
│ │ │   ├── balanced-match@0.2.0
│ │ │   └── concat-map@0.0.1
│ │ └─┬ once@1.3.2
│ │   └── wrappy@1.0.1
│ ├─┬ handlebars@3.0.3
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.3
│ │ ├─┬ source-map@0.1.43
│ │ │ └── amdefine@0.1.0
│ │ └─┬ uglify-js@2.3.6
│ │   ├── async@0.2.10
│ │   └─┬ optimist@0.3.7
│ │     └── wordwrap@0.0.3
│ ├── marked@0.3.3
│ ├─┬ natural@0.1.29
│ │ ├── apparatus@0.0.9
│ │ ├── sylvester@0.0.21
│ │ └── underscore@1.8.3
│ ├── wrench@1.5.8
│ └─┬ yargs@3.9.1
│   ├── camelcase@1.1.0
│   ├─┬ cliui@2.1.0
│   │ ├─┬ center-align@0.1.1
│   │ │ └─┬ align-text@0.1.1
│   │ │   ├── kind-of@1.1.0
│   │ │   ├── longest@1.0.1
│   │ │   └── repeat-string@1.5.2
│   │ ├─┬ right-align@0.1.1
│   │ │ └─┬ align-text@0.1.1
│   │ │   ├── kind-of@1.1.0
│   │ │   ├── longest@1.0.1
│   │ │   └── repeat-string@1.5.2
│   │ └── wordwrap@0.0.2
│   ├── decamelize@1.0.0
│   └── window-size@0.1.0
```

**Comment by rkichenama** [comment] 2015-11-19 20:04
@JeremiePat I'm not totally sure, but those trees are identical

**Comment by matthewferry** [comment] 2015-11-20 06:55
yeah those are identical trees. I'm having the same issue with fresh installs of 2.1.0

```

Unknown argument: xdemo

Details:
    killed: false
    code: 1
    signal: null
    stdout: 
    stderr: Usage: kss-node [options]
```

**Comment by ryuran** [comment] 2015-11-20 08:27
Hello,

Error of copy/past i think.
```
─┬ kss@2.1.0
  ├─┬ glob@4.5.3
  │ ├─┬ inflight@1.0.4
  │ │ └── wrappy@1.0.1
  │ ├── inherits@2.0.1
  │ ├─┬ minimatch@2.0.10
  │ │ └─┬ brace-expansion@1.1.1
  │ │   ├── balanced-match@0.2.1
  │ │   └── concat-map@0.0.1
  │ └─┬ once@1.3.2
  │   └── wrappy@1.0.1
  ├─┬ handlebars@3.0.3
  │ ├─┬ optimist@0.6.1
  │ │ ├── minimist@0.0.10
  │ │ └── wordwrap@0.0.3
  │ ├─┬ source-map@0.1.43
  │ │ └── amdefine@1.0.0
  │ └─┬ uglify-js@2.3.6
  │   ├── async@0.2.10
  │   └─┬ optimist@0.3.7
  │     └── wordwrap@0.0.3
  ├── marked@0.3.5
  ├─┬ natural@0.1.29
  │ ├── apparatus@0.0.9
  │ ├── sylvester@0.0.21
  │ └── underscore@1.8.3
  ├── wrench@1.5.8
  └─┬ yargs@3.30.0
    ├── camelcase@1.2.1
    ├─┬ cliui@3.0.3
    │ ├─┬ string-width@1.0.1
    │ │ ├─┬ code-point-at@1.0.0
    │ │ │ └── number-is-nan@1.0.0
    │ │ └─┬ is-fullwidth-code-point@1.0.0
    │ │   └── number-is-nan@1.0.0
    │ ├─┬ strip-ansi@3.0.0
    │ │ └── ansi-regex@2.0.0
    │ └── wrap-ansi@1.0.0
    ├── decamelize@1.1.1
    ├─┬ os-locale@1.4.0
    │ └─┬ lcid@1.0.0
    │   └── invert-kv@1.0.0
    ├── window-size@0.1.4
    └── y18n@3.2.0
```
Tree from @JeremiePat works but this one dosn't.

**Comment by JeremiePat** [comment] 2015-11-20 10:00
Yes, thanks @ryuran :)

**Comment by JohnAlbin** [comment] 2015-11-21 05:01
I just tested this and its definitely yargs. It keeps causing issues. New semver versions break backwards compatibility often. :-((((

I'll release a 2.1.1 today and nail yargs version to a tree so it won't accept any newer "compatible" versions that might break kss-node.

**Comment by JohnAlbin** [comment] 2015-11-21 05:11
Actually, this is a duplicate of #236

**Closed by JohnAlbin** 2015-11-21 05:11 UTC
