### ISSUE TITLE
Windows bug

### ISSUE THREAD

**Issue by foued611** [kss-node/kss-node#242] opened 2015-11-20 13:39 UTC
kss-node Versiion: 2.1
Node: 0.10 & 4.2
Windows 8 & 10
it seems that the command arguments have not been passed.
```
Running "kss:dist" (kss) task
>> kss-node --css styles/master.css ".temp/docs/" "docs/styles/"
>> Error: Command failed: C:\Windows\system32\cmd.exe /s /c "node C:\dev\bla\eci\bla-int\node_modules\kss\bin\kss-node --css styles\master.css ".temp\docs/" "docs\styles/""
>> Usage: kss-node [options]
>> 
>> Options:
>>   --init, -i      Clone a style guide template to customize             [string]
>>   --template, -t  Use a custom template to build your style guide
>>                                                               [string] [default:
>>   "node_modules\\grunt-kss-node\\node_modules\\kss\\generator\\handlebars\\templ
>>                                                                            ate"]
>>   --mask, -m      Use a mask for detecting files containing KSS comments
>>                 [string] [default: "*.css|*.less|*.sass|*.scss|*.styl|*.stylus"]
>>   --css           URL of a CSS file to include in the style guide       [string]
>>   --js            URL of a JavaScript file to include in the style guide[string]
>>   --custom        Process a custom property name when parsing KSS comments
>>                                                                         [string]
>>   --source        Source directory to parse for KSS comments            [string]
>>   --destination   Destination directory of generated style guide
>>                                                 [string] [default: "styleguide"]
>>   --config, -c    Load the kss-node configuration from a json file
>>   --helpers       Location of custom handlebars helpers; see
>>                   http://bit.ly/kss-wiki                                [string]
>>   --homepage      File name of the homepage's Markdown file
>>                                              [string] [default: "styleguide.md"]
>>   --placeholder   Placeholder text to use for modifier classes
>>                                           [string] [default: "[modifier class]"]
>>   --title         Title of the style guide [string] [default: "KSS Style Guide"]
>>   --help, -h, -?  Show help                                            [boolean]
>>   --version       Show version number                                  [boolean]
>> 
>> Unknown argument: xdemo
>> Code: Usage: kss-node [options]
>> 
>> Options:
>>   --init, -i      Clone a style guide template to customize             [string]
>>   --template, -t  Use a custom template to build your style guide
>>                                                               [string] [default:
>>   "node_modules\\grunt-kss-node\\node_modules\\kss\\generator\\handlebars\\templ
>>                                                                            ate"]
>>   --mask, -m      Use a mask for detecting files containing KSS comments
>>                 [string] [default: "*.css|*.less|*.sass|*.scss|*.styl|*.stylus"]
>>   --css           URL of a CSS file to include in the style guide       [string]
>>   --js            URL of a JavaScript file to include in the style guide[string]
>>   --custom        Process a custom property name when parsing KSS comments
>>                                                                         [string]
>>   --source        Source directory to parse for KSS comments            [string]
>>   --destination   Destination directory of generated style guide
>>                                                 [string] [default: "styleguide"]
>>   --config, -c    Load the kss-node configuration from a json file
>>   --helpers       Location of custom handlebars helpers; see
>>                   http://bit.ly/kss-wiki                                [string]
>>   --homepage      File name of the homepage's Markdown file
>>                                              [string] [default: "styleguide.md"]
>>   --placeholder   Placeholder text to use for modifier classes
>>                                           [string] [default: "[modifier class]"]
>>   --title         Title of the style guide [string] [default: "KSS Style Guide"]
>>   --help, -h, -?  Show help                                            [boolean]
>>   --version       Show version number                                  [boolean]
>> 
>> Unknown argument: xdemo
```

**Comment by JohnAlbin** [comment] 2015-11-21 05:02
Error messages is a duplicate of #240

**Closed by JohnAlbin** 2015-11-21 05:02 UTC
