### ISSUE TITLE
Query, get css/sass/less source associated with a comment block

### ISSUE THREAD

**Issue by vidhill** [kss-node/kss-node#269] opened 2016-02-02 16:25 UTC
Is it possible to get the source associated/that follows a comment block e.g.

If I wanted to have my colour variables in a sass file:
```scss
//
// My Global Colour Variable
//
// These are the default set of colours.for the styleguide
// Markup: colour-chips.html

$colour1: #FFF;
$colour2: #EEE;
$colour3: #666;
````

If I wanted to get the sass to access the actual hex values (to output and display in my style guide) how would I go about this?

**Comment by JohnAlbin** [comment] 2016-02-11 02:28
Duplicate of #50

**Closed by JohnAlbin** 2016-02-11 02:28 UTC
