### ISSUE TITLE
Expand to Fullscreen Component

### ISSUE THREAD

**Issue by RobLoach** [kss-node/kss-node#333] opened 2016-06-17 15:02 UTC
When clicking the "Expand" button, it opens a new window, with just the component and CSS on the page, allowing for Full Screen previews on the components on their own.

**Comment by thiagodemellobueno** [comment] 2016-06-17 17:07
I dig.

Earlier today I was thinking about how we could test using kalastatic, for some presos (and make them supersweet thusly). This makes that easier!

**Comment by RobLoach** [comment] 2016-06-17 17:24
Definitely, I would find this particularly helpful when demonstrating layouts, and maybe even compiling multiple atoms/molecules/components together for large demos.

**Comment by JohnAlbin** [comment] 2016-11-01 15:04
Duplicate of #165

**Closed by JohnAlbin** 2016-11-01 15:04 UTC
