### ISSUE TITLE
Reference sections from within markdown description?

### ISSUE THREAD

**Issue by airtonix** [kss-node/kss-node#460] opened 2018-02-27 05:06 UTC
Would be great to link to other sections in documentation.

Something like:

```
/*
Base thing

A base for things.

Markup:
<div class="thing {{default classes modifier_class}}"></div>

Styleguide Core.Things.Base
*/
```
```
/*
A complex thing. See [Base](Core.Things.base) for more info.

Markup:
{{#> Core.Things.Base classes="complex-thing"}}
...
{{/Core.Things.Base}}

Styleguide Core.Things.Complex
*/
```

**Comment by ryuran** [comment] 2018-03-22 14:19
@airtonix It's a duplicate of #351

**Closed** 2018-04-05 14:00 UTC
